name: angular-app

on:
  push:
    branches: 
       - master

jobs:
  build:
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        node-version: [18]    

    steps:
    - uses: actions/checkout@v3
    - name: Install node js
      uses: actions/setup-node@v3
      with:  
        node-version: 18.x
    - name: Install NPM Dependencies
      run: |
        npm i
        npm test
    - name: make zip file 
      run: |
        sudo zip -r angular.zip . -x ".github" -x ".git" -x "README.md"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: angular.zip
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package
      - name: SSH deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          source: "angular.zip"
          target: "/var/www/html/angular-app/"

      - name: SSH deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}} 
          script: |
          sudo unzip /var/www/html/angular-app/angular.zip -d /var/www/html/angular-app/
          sudo rm -r /var/www/html/angular-app/angular.zip